# Generated by Django 4.1 on 2022-11-15 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0002_portfolio_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='about1',
            field=models.TextField(blank=True, verbose_name='About1'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='about2',
            field=models.TextField(blank=True, verbose_name='About2'),
        ),
    ]
