# Generated by Django 4.1 on 2022-11-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0004_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='datestarted',
            field=models.DateTimeField(default=None, verbose_name='Date Started'),
            preserve_default=False,
        ),
    ]
