# Generated by Django 4.1 on 2022-11-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0008_alter_experience_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=150, verbose_name='School')),
                ('degree', models.CharField(blank=True, max_length=150, verbose_name='Degree')),
                ('field', models.CharField(blank=True, max_length=150, verbose_name='Field')),
                ('track', models.CharField(blank=True, max_length=150, verbose_name='Track')),
                ('start_date', models.DateTimeField(verbose_name='Date Started')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Date Ended')),
                ('is_current', models.BooleanField(blank=True, verbose_name='Is Current')),
                ('gpa', models.CharField(blank=True, max_length=5, verbose_name='GPA')),
            ],
        ),
    ]
